version: '3.8'

services:
  github-radar:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./data/prod.db
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - CRON_SECRET=${CRON_SECRET}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - github-radar
    restart: unless-stopped
    profiles: ["production"]

  # Optional: Add a cron job scheduler
  cron-scheduler:
    image: curlimages/curl:latest
    volumes:
      - ./scripts:/scripts:ro
    environment:
      - CRON_SECRET=${CRON_SECRET}
      - APP_URL=${NEXT_PUBLIC_APP_URL:-http://github-radar:3000}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while true; do
          echo "Running scheduled sync at $(date)"
          curl -X POST -H "Authorization: Bearer $$CRON_SECRET" $$APP_URL/api/cron/sync
          sleep 3600  # Run every hour
        done
    depends_on:
      - github-radar
    restart: unless-stopped
    profiles: ["with-scheduler"]